"use client";

import { useEffect, useState } from "react";
import { X, Download, History } from "lucide-react";
import { createClient } from "@/utils/supabase/client";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type AuditEntry = {
  id: string;
  project_id: string;
  user_email?: string | null;
  action_type: string;
  description: string;
  created_at: string;
};

interface AuditLogModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectId: string;
  projectName?: string;
}

function formatAuditDate(dateStr: string): string {
  const d = new Date(dateStr);
  const day = String(d.getDate()).padStart(2, "0");
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const year = d.getFullYear();
  const hours = String(d.getHours()).padStart(2, "0");
  const minutes = String(d.getMinutes()).padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

export function AuditLogModal({
  isOpen,
  onClose,
  projectId,
  projectName = "Project",
}: AuditLogModalProps) {
  const [logs, setLogs] = useState<AuditEntry[]>([]);
  const [loading, setLoading] = useState(false);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    if (!isOpen || !projectId) return;

    const fetchLogs = async () => {
      setLoading(true);
      const supabase = createClient();

      const { data, error } = await supabase
        .from("project_audit_log")
        .select("*")
        .eq("project_id", projectId)
        .order("created_at", { ascending: false });

      if (error) {
        console.error("Error fetching audit log:", error);
        setLogs([]);
      } else {
        setLogs((data as AuditEntry[]) ?? []);
      }
      setLoading(false);
    };

    fetchLogs();
  }, [isOpen, projectId]);

  const generateAuditPDF = () => {
    if (!projectName) return;

    setExporting(true);
    const doc = new jsPDF();
    const dateStr = new Date().toLocaleDateString();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(51, 65, 85);
    doc.text("EQUILY", 14, 20);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Project Audit Trail", 14, 26);
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Project: ${projectName}`, 14, 35);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Download date: ${dateStr}`, 14, 42);

    const tableData: [string, string, string, string][] =
      logs.length > 0
        ? logs.map((h) => [
            formatAuditDate(h.created_at),
            h.user_email ?? "—",
            h.action_type,
            h.description,
          ])
        : [["No actions recorded yet", "—", "—", "—"]];

    autoTable(doc, {
      startY: 50,
      head: [["Date", "User", "Action", "Description"]],
      body: tableData,
      theme: "grid",
      headStyles: { fillColor: [44, 62, 80], textColor: [255, 255, 255], fontStyle: "bold" },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 38 },
        1: { cellWidth: 32 },
        2: { cellWidth: 45 },
        3: { cellWidth: "auto" },
      },
    });

    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Page ${i} of ${pageCount} - Generated by Equily`, 105, 290, { align: "center" });
    }

    doc.save("Project_Audit_Trail.pdf");
    setExporting(false);
  };

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-[110] flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4"
      onClick={onClose}
    >
      <div
        className="w-full max-w-2xl bg-white rounded-[32px] shadow-2xl p-8 animate-in zoom-in duration-200 font-sans max-h-[90vh] overflow-hidden flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex justify-between items-center mb-6">
          <div className="flex items-center gap-2">
            <History className="w-5 h-5 text-emerald-600" />
            <h3 className="font-black text-slate-800 text-lg uppercase tracking-tight">
              Audit Log
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-full text-slate-400 transition-colors"
            aria-label="Close"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {loading ? (
          <div className="py-12 text-center text-slate-400 font-bold">Loading...</div>
        ) : (
          <>
            <div className="flex-1 overflow-auto pr-2 custom-scrollbar mb-6">
              {logs.length === 0 ? (
                <p className="text-center py-8 text-slate-400 italic">No actions recorded yet.</p>
              ) : (
                <table className="w-full text-left border-collapse text-sm">
                  <thead>
                    <tr className="text-[10px] font-bold text-slate-400 uppercase tracking-wider border-b border-slate-200">
                      <th className="py-3 px-4">Date</th>
                      <th className="py-3 px-4">User</th>
                      <th className="py-3 px-4">Action</th>
                      <th className="py-3 px-4">Description</th>
                    </tr>
                  </thead>
                  <tbody className="text-slate-700">
                    {logs.map((entry) => (
                      <tr key={entry.id} className="border-b border-slate-50 hover:bg-slate-50/50">
                        <td className="py-3 px-4 font-medium text-slate-500 whitespace-nowrap">
                          {formatAuditDate(entry.created_at)}
                        </td>
                        <td className="py-3 px-4">{entry.user_email ?? "—"}</td>
                        <td className="py-3 px-4 font-bold text-slate-800">{entry.action_type}</td>
                        <td className="py-3 px-4 max-w-[280px] truncate" title={entry.description}>
                          {entry.description}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>

            <button
              onClick={generateAuditPDF}
              disabled={exporting}
              className="w-full flex items-center justify-center gap-2 rounded-xl bg-slate-900 text-white py-3 font-bold hover:bg-slate-800 transition-all disabled:opacity-50"
            >
              <Download className="w-5 h-5" />
              {exporting ? "Exporting..." : "Export PDF"}
            </button>
          </>
        )}
      </div>
    </div>
  );
}
